config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'pages/home'

  root 'relationships#index'

  resources :relationships do
    resources :reminders 
  end

end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  RELATIONSHIP_TYPES = ["Family", "Professional Network", "Mentor", "Mentee"]

  belongs_to :user
  has_many :reminders

  validates :name, presence: true
  validates :relationship_type, presence: true

  def reminders_due_in(days)
    one_week_from_now = Date.today() + days
    reminders.select{|r| one_week_from_now > r.due_date}
  end

  def reminders_by_status(status = 'all')
    if status == 'all'
      results = self.reminders
    else
      results = self.reminders.select{|r| r.status == status}
    end
    #results.sort_by!(:created_at)
  end

  def update_reminder_statuses
    reminders.each {|r| r.update_status}
  end

  private
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  belongs_to :relationship

  FREQUENCIES = ["Daily", "Weekly", "Monthly", "Quarterly", "Yearly"]
  STATUSES = ['active', 'late', 'completed']

  before_validation :set_defaults
  after_update :create_next_reminder

  validates :frequency, presence: true
  validates :due_date, presence: true

  def set_defaults
    self.due_date ||= Date.today() + frequency_in_days.days
    self.status ||= 'active'
  end

  def update_status
    if due_date < Date.today() + 2.days && self.status != 'completed'
      self.update_attribute(:status, 'late') 
    end
  end

  def completed?
    self.status == 'completed'
  end

  private
  def create_next_reminder
    return unless self.completed?
    self.relationship.reminders.create(
      status: 'active', 
      frequency: self.frequency, 
      note: self.note,
      due_date: self.due_date = self.due_date + frequency_in_days.days
    )
  end

  def frequency_in_days
    return 0 if self.frequency.blank?
    day_mapping = { 
      "Daily" => 1,
      "Weekly" => 7,
      "Monthly" => 30,
      "Quarterly" => 90,
      "Yearly" => 365
    }
    day_mapping[self.frequency]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  # include ActionView::Helpers::TagHelper
  
  has_many :relationships
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!

  def show
    @relationship = current_user.relationships.find(params[:id])
    @reminder ||= @relationship.reminders.build
  end

  def index
    @relationships = current_user.relationships.all
  end

  def update
    @relationship = current_user.relationships.find(params[:id])
    if @relationship.update(relationship_params)
      redirect_to @relationship
    else
      render 'edit'
    end
  end

  def edit
    @relationship = current_user.relationships.find(params[:id])
  end

  def destroy
    @relationship = current_user.relationships.find(params[:id])
    @relationship.destroy

    redirect_to relationships_path
  end


  def create
    @relationship = current_user.relationships.create(relationship_params)
    @relationship.reminders.create(reminder_params)

    if @relationship.save
      redirect_to relationships_path
    else
      render 'new'
    end
  end

  def new
    @relationship = Relationship.new
    @reminder = @relationship.reminders.new
  end

  private
  def relationship_params
    params.require(:relationship).permit(:name, :relationship_type)
  end
  def reminder_params
    params[:relationship].require(:reminder).permit(:date, :note, :frequency, :status, :due_date)
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController
  def show
    @relationship = Relationship.find(params[:relationship_id])
    @reminder = Reminder.find(params[:id])
  end

  def edit
    @reminder = Reminder.find(params[:id])
  end

  def update
    @reminder = Reminder.find(params[:id])
    @reminder.update_attributes(reminder_params)

    redirect_to relationship_path(@reminder.relationship)
  end

  def create
    @relationship = Relationship.find(params[:relationship_id])
    @reminder = @relationship.reminders.create(reminder_params)

    if @reminder.save
      redirect_to relationship_path(@relationship)
    else
      render 'relationships/show'
    end
  end

  def destroy
    @relationship = Relationship.find(params[:relationship_id])
    @reminder = @relationship.reminders.find(params[:id])
    @reminder.destroy

    redirect_to relationship_path(@relationship)
  end

  private
  def reminder_params
    params.require(:reminder).permit(:date, :note, :frequency, :status, :due_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
  def next_reminder_due_in(relationship)
    due_date = relationship.reminders.minimum(:due_date) || nil
    distance_of_time_in_words(Time.now(), due_date) if due_date
  end
end

app/helpers/reminders_helper.rb
module RemindersHelper
  def prettify(reminder)
    due_date = reminder.due_date.strftime("%b %e")

    label_class = {
      "active" => 'label-success',
      "late"=> 'label-warning',
      "completed" => 'label-default'
    }

    label = content_tag(:div, reminder.status, class: "label #{label_class[reminder.status]}")
    return label + " #{due_date} #{reminder.frequency} #{reminder.note}"
  end
end

app/views/layouts/_flash.html.slim
= content_tag(:p, notice, class: "alert alert-success") if notice
= content_tag(:p, alert, class: "alert alert-danger") if alert

app/views/layouts/_header.html.slim
nav.navbar.navbar-dark.bg-primary
  .container
    = link_to "Project Joylon", root_url, class: "navbar-brand"
    ul.nav.navbar-nav.pull-xs-right
      - if user_signed_in?
        li.nav-item = link_to "Your Relationships", relationships_path, class: "nav-link"
        li.nav-item = link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link"
      - else
        li.nav-item = link_to "Log In", new_user_session_path, class: "nav-link"
        li.nav-item = link_to "Register", new_user_registration_path, class: "nav-link"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
    = stylesheet_link_tag    'application', media: 'all'
    = csrf_meta_tags
    meta name="viewport" content="width=device-width, initial-scale=1" 
  body
    = render 'layouts/header'
    .container.m-t-3
      = render 'layouts/flash'
      = yield
    = javascript_include_tag 'application', async: Rails.env.production?

app/views/pages/home.html.slim
.jumbotron
  h1 Project Joylon!
  p Welcome streamers!

app/views/relationships/_form.html.slim
= simple_form_for @relationship, class: 'form-control' do |f|
  - @relationship.errors.full_messages.each do |msg|
    = render partial: 'layouts/flash', locals: {alert: "Could not save because #{msg}."}
  = f.input :name, placeholder: "e.g. Thomas Jefferson"
  = f.input :relationship_type, class: 'form-control', collection: Relationship::RELATIONSHIP_TYPES, prompt: "Who is this person to you?"
  = f.simple_fields_for :reminder, @relationship.reminders.build do |r|
    = r.input :frequency, prompt: 'Frequency', collection: Reminder::FREQUENCIES
    = r.input :note, placeholder: 'Add any notes about this reminder.'
  = f.button :submit, class: 'btn btn-primary'

app/views/relationships/_reminders_list.html.slim
h3=status.titleize + " Reminders"
ul
- relationship.reminders_by_status(status).each do |reminder|
  li
    = prettify(reminder)
    .actions.pull-right
      - unless reminder.completed?
        = simple_form_for [reminder.relationship, reminder], method: :patch, wrapper: :inline_form, html: {class: 'pull-right'} do |f| 
          = f.input :status, input_html: { value: 'completed'}, as: :hidden, wrapper_class: ''
          = f.submit 'Complete', class: 'btn btn-link text-success btn-sm'
      = link_to 'View', [reminder.relationship, reminder], class: 'btn btn-link btn-sm'
      = link_to 'Delete', [reminder.relationship, reminder], method: :delete, class: 'btn btn-link btn-sm text-danger'
    .clearfix

app/views/relationships/edit.html.slim
h1 Edit Relationship

= render 'form'

app/views/relationships/index.html.slim
h1 Dashboard
= link_to 'Create New Relationship', new_relationship_path, class: 'btn btn-primary pull-right'

br
hr

h3 Relationships
table.table.col-md-9
  tr
    th Name
    th Relationship
    th Due In
    th Actions
  - @relationships.each do |relationship|
    tr
      td= link_to relationship.name, relationship_path(relationship)
      td= relationship.relationship_type
      td= next_reminder_due_in(relationship)
      td
        /= link_to "Mark Complete", "#", class: 'btn btn-sm btn-secondary'
        = link_to "View", relationship_path(relationship), class: 'btn btn-sm btn-secondary'
        = link_to "Delete", relationship_path(relationship), method: :delete, class: 'btn btn-sm btn-danger'

app/views/relationships/new.html.slim
h1 Create New Relationship

= render 'form'

app/views/relationships/show.html.slim
.col-md-8
  .pull-right
    = link_to "Edit", edit_relationship_path(@relationship), class: 'btn btn-secondary btn-sm'
    = link_to "Delete", @relationship, method: :delete, class: 'btn btn-danger btn-sm'
  h2 #{@relationship.name}
  - @relationship.errors.full_messages.each do |msg|
    = render partial: 'layouts/flash', locals: {alert: "Could not save because #{msg}."}

  .description
    b Type of Relationship: 
    =@relationship.relationship_type


  hr

  = render partial: 'relationships/reminders_list', locals: {relationship: @relationship, status: 'late'}
  = render partial: 'relationships/reminders_list', locals: {relationship: @relationship, status: 'active'}
  = render partial: 'relationships/reminders_list', locals: {relationship: @relationship, status: 'completed'}
  /= link_to "Manual Refresh Statuses", , class: 'btn btn-sm btn-secondary pull-right'

.col-md-4
  h2 Add a reminder
  = render 'reminders/form'

app/views/reminders/_form.html.slim
- @reminder.errors.full_messages.each do |msg|
  = render partial: 'layouts/flash', locals: { alert: msg }
= simple_form_for [@relationship, @reminder], wrapper: :inline_form do |f|
  = f.input :frequency, prompt: 'Frequency', collection: Reminder::FREQUENCIES
  /= f.input :status, collection: Reminder::STATUSES, prompt: 'Status'
  = f.input :note, placeholder: 'Add any notes about this reminder.'
  = f.submit class: 'btn btn-primary'

app/views/reminders/edit.html.slim
= render 'form'

app/views/reminders/show.html.slim
h1 Update Reminder
= render 'form'